services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: flaskdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      ENVIRONMENT: local
      DATABASE_URL: postgresql://postgres:postgres@db:5432/flaskdb
    depends_on:
      - db